---
title: "Shiny Workflows: Tutorial 1"
output: 
  html_document:
    toc: false
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pre-readings

- [Chapter 1: Git](https://b-klaver.github.io/shinyWorkflows/git.html)   
- [Chapter 2: Package Development](https://b-klaver.github.io/shinyWorkflows/package-development.html)   

## Assignment

### 1) Clone PHMRSapp

Clone the [PHMRSapp repository](http://lvmgenodh01.phsabc.ehcnet.ca/bccdc/das/core-das/phmrsapp) from Gitlab to your local `U:/` drive. Spend some time familiarizing yourself with the codebase and notice how some of the package development tools were used to build it.

### 2) Create a practice project

Create a project in your `U:/` drive that we can use throughout these tutorials. This project should include:

#### a) Git

- Initiate Git, make some test commits and get a feel for using git in a project.   
- Create a repository on Gitlab and link this project to that repository.   

#### b) Package structure

- Create a `DESCRIPTION` file
- Create a practice script to test `devtools::load_all()`, as well as roxygen2 documentation using `devtools::document()`
- Feel free to continue to play around with other features discussed in the package chapter

### 3) Readings

- [Chapter 3: Shiny](https://b-klaver.github.io/shinyWorkflows/shiny.html)
